# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-22 23:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courses',
            old_name='course_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='courses',
            old_name='course_name',
            new_name='name',
        ),
    ]
